const quote = () => {
    return ( 
        <div>
            <p>Small daily improvements are the key to staggering long-term results.</p>
            <p>James Clear</p>
            <p>Generated by ChatGPT</p>
        </div>
    );
}
 
export default quote;